### ISSUE TITLE
MongoDB on remote/different host than API

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-API#22]
- [x] specify remote host / remote port
- [ ] specify  DB

want to be able to point to a MondoDB not hosted on the same server/vm as the API 

=> update code + param file (.env ? )

go run ./main.go --db HOME
connected to HOME@mydbhost.mydomain with token "myhometoken"

in config file.. or somewhere 

[HOME]
dbhost: db.chibois.net:27123
dbtoken: myhometoken
dbname:HOME

[WORK]
dbhost: 1.2.43.4:27222
dbtoken: myworktoken
dbname:CUSTOMER

[ZIADPC]
dbhost: localhost:27222
dbtoken: ziadtoken
dbname: ZIAD

**Comment by denizul** [comment]
This is risky
