### ISSUE TITLE
API  : generic request + details

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-API#25]
= generic request  = 

("GET")	,"/api/{object}/{id}/?detail=0|1|2|3|4"

               tenant + detail=4 => tenant / site / building / rooms / racks
<object> = tenant / sites / buildings / rooms / racks / devices

for non pertinent objects such as : groups / acs / powerpanel / seprator / corridor 
- NO OK to include them in global generic request ? 
- OK but result is empty ?

Ziad K: {{URL}}/api/tenants/{{TenantName}}/all/sites/buildings/rooms
Ziad K: (pour tenant -> rooms)

Cedrok :  {{URL}}/api/devices/{{chassisName}}/all/devices/devices/devices/.....
cedrok :  (pour devices -> devices / devices /devices )

room : rack / group / acs / mdi / corridor / cupboard

**Comment by denizul** [comment]
I added ?limit=# requests and they seem to be working fine
