### ISSUE TITLE
move jenkins pipeline out of OGrEE VM

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-API#31]
please move CI pipeline out of main OGrEE VM (formerly "netbox"')

ci.ogree.ditrit.io on dedicated jenkins container (LXC) under server

please remove any /home/ziad for your code
replace by /OGrEE-jenkins

please use ci2.ogree.ditrit.io instead

thx ;-)

**Comment by denizul** [comment]
The job is finished
