### ISSUE TITLE
Add {strays} collection. 

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-API#35]
Add orphans/strays objects

-  as devices 
- with parentID = NULL
- category = device 
- category may me also other future object such as 'vm', 'cluster', '...

- [x] Create Orphan + children (not orphan)

``` 
+stray:<category >@name@<other parameters>
+device@name.proc1@...
+device@name.interface @...
```
category : device | ... | virtualmachine | cluster ...

- [ ] Link stray to a parent
 ```
link:aws2@TENANT.SITE.BUILDING.ROOM.RACK@slot
link:child@parent@slot
link:child@parent@posU
```
=> aws2 is moved from {stray} to {devices}

unlink ?

**Comment by denizul** [comment]
This is done on the API side
