### ISSUE TITLE
Model Json to check Json

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-API#38]

**Comment by helderbetiol** [comment]
The idea is to validate and guarantee the right format of requests sent / received by the API. For the moment, some validate functions in validateEntity verify the existence of some attributes in received requests and some formats (check if posXYZ is a Vector, for example). To expand this, some options are available :

- Keep right validation code directly in validateEntity;
- Use a validation library, such as: [gookit/validate](https://github.com/gookit/validate)
- Use [JSON Schema](https://json-schema.org), with a helper package like [jsonschema](https://pkg.go.dev/github.com/santhosh-tekuri/jsonschema/v5#section-readme)

The third option is a more generic solution that would create schemas that could also be used by other applications that want to communicate with the API, like the CLI and the Flutter app backend. So let's try that one!

**Comment by helderbetiol** [comment]
JSON Schemas added! Check them out in models/schemas/.
Each entity has its own schema ([entityName]_schema.json), except for AC, Cabinet and Panel that share the same base_schema.json.
Inside models/schemas/refs, you will find:
- base.json: a base shared schema of properties used by most entities (name, category, domain, etc.) and imported by entity schemas with "$ref": "refs/base.json". 
- types.json: defines some data types/formats to validate that are regularly seen in the schemas, such as _vector2_ and _color_.

The models.validateEntity function has been modified to call the jsonschema validation. 

To test a json file against the schemas without using the API, you can install the [jsonschema CLI](https://pkg.go.dev/github.com/santhosh-tekuri/jsonschema/v5@v5.2.0#readme-cli):
`go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest`
`jv site_test.json site_schema.json`

**Comment by helderbetiol** [comment]
Pending:
If unexpected properties are sent in a request to the API (in a POST to create a site, for example), those properties should be ignored and not added to the database, but the request can still be accepted and a 200 status code returned. Currently, they are added to the database.
