### ISSUE TITLE
rack position with "Z" : Vector3

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-API#42]
Rack position should be Vector2 (rack on floor) or Vector3

=> API to be modified
=> CLI to be modified

**Comment by helderbetiol** [comment]
The idea is to implement a new mandatory attribute to create a rack that replaces the current posXY: poXYZ. Its value will always be a Vector3, for example: {"x":25.0,"y":29.4,"z":5.0}". In the cases where a Vector2 would have been enough, a Vector3 will be sent with the z coordinate set to 0.

To implement it on the API side, we should verify that posXYZ is in the attributes list and in a valid Vector3 format.
