### ISSUE TITLE
Add endpoint to get temperature Unit

### ISSUE THREAD

**Issue by Novanef** [ditrit/OGrEE-API#43]
All sites have (hopefully) a  "temperatureUnit" attribute. Unity needs an endpoint to get the temperature unit of a site using the id of an object present in the site. For example, `/api/tempUnits/[id]`

I.e, if we have TENANT1.SITE1.BUILDING1.ROOM1.RACK1, if RACK1's id is 123 and SITE1's temperature unit is "°C", a GET request to `/api/tempUnits/123` should return "°C"

**Comment by helderbetiol** [comment]
Added new /api/tempunits/{id} endpoint. The id of any object can be sent. Using the parentId, the API will search for the object's parent until it finds a site (category), then it returns the site's temperatureUnit attribute in the following format:
{"data":{"temperatureUnit":"°C"},"message":"successfully got temperatureUnit from object's parent site","status":true}

If id not found or parent site not found (in case of a tenant, for example), an error message is returned with status code 404.
