### ISSUE TITLE
Conditional Header Support and Filtering

### ISSUE THREAD

**Issue by denizul** [ditrit/OGrEE-API#46]
For more advanced queries to the API, I think this will be very important. For example:
1) I want all devices created this month
2) I want to get all the racks but only their names 

We can achieve this by adding keywords in the Headers (such as: date >= xyz && filterKeep=xyz && filterOut=xyz)

This will make the API more feature filled and robust by responding to the client according to the conditions described by the incoming header. Refer to:
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/perform-conditional-operations-using-web-api

This will also be better in order to maintain consistency among clients of a customer. They can use conditions so that they can optimistically send requests to the API without fear of stale or inconsistent data

**Comment by hchybz** [comment]
for dcTRACK API, see in doc : 

filter API REST with a json payload
 ```
### DELL : cat /tmp/dctrack_search_models_dell_poweredge.json
{"columns": [
   { "name": "cmbMake",    "filter": { "in": ["Dell"]     } },
   { "name": "tiClass",    "filter": { "in": ["Device"]   } },
   { "name": "tiMounting", "filter": { "in": ["Rackable"] } },
   { "name": "model",      "filter": { "contains": "poweredge" } },
    {"name":"tiSubclass", "filter":{"eq":"Standard"}}
   ]
   ,"selectedColumns": [
                        {"name": "name"},
                        {"name": "dimWidth"},
                        {"name": "dimDepth"},
                        {"name": "dimHeight"},
                        {"name": "Weight"},
                        {"name": "tiSubclass"},
                        {"name": "tiRuHeight"}
                    ]
}
```

we could copy this ..a bit heavy but powerful
