### ISSUE TITLE
dbforTenants : add +domain in /Organization

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-API#50]
in order to start implementing dbForTenant featuren we need to replace the existing tenant in /Physical by domain in /Organization

Here are the steps
- dbforTenant uptodate with master (done)
- add /api/domains in API+MongoDB (POST/PATCH/PUT/DELETE) : for start, only the same attributes as we already have in tenant
- swagger updated
- add +domain:<DOMAIN>@<color> in CLI (other issue)

when API+CLI with +domain are ok, 3D will be adapted

**Comment by denizul** [comment]
The only thing to do here is to test the CLI with the API, there is nothing to do on the API side as of  ee55da24a

**Comment by denizul** [comment]
There was nothing to do here on the API. This funciton was merged into dbForTenants branch in the CLI. The new feature is that we can create domains in the CLI (https://github.com/ditrit/OGrEE-CLI/pull/153):
```
+domain:path/to/domain@6DigitHexColor
```
