### ISSUE TITLE
Wrong message when getting a  building template

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-API#52]
In a the response for getting building template, the API's message should be "successfully got building_template" as we already have "successfully got room_template" for a room & "successfully got obj_template" for an object

```json
    "data":
	{
		"category":"bldg-template",
		"createdDate":"2023-02-01T14:22:31.969Z",
		"id":"63da75a77fcd61a9d3d0d4e0",
		"lastUpdated":"2023-02-01T14:22:31.969Z",
		"sizeWDHm":[42,104,5],
		"slug":"edf-noe-bi1",
		"vertices":[]
	},
	"message":"successfully got object",
	"status":true
}
```

**Comment by helderbetiol** [comment]
It was also brought to our attention that category is overwritten by the API with the endpoint name. 
For templates, the desired behavior is to keep category as it was sent. 
For objects, to check if the category and endpoint match (and refuse the request, if not) is a better approach. 
This is also being implemented with this issue
